### ISSUE TITLE
Get deeplink function got error

### ISSUE THREAD

**Issue by Tr14** [oracle-samples/pushiomanager-flutter#12]
When I added:

 PushIOManager.setNotificationDeepLinkHandler((String url) {
      print("Deeplink: $url");
 });

it returns the error: The argument type 'void Function(String)' can't be assigned to the parameter type 'void Function(String?)'

Please help me check the image below.

![image](https://github.com/oracle-samples/pushiomanager-flutter/assets/31535880/5785e6ae-3bff-4652-965f-962ceb7038e1)

Thanks,
Truc

**Comment by jamieastley** [comment]
I would suggest _reading_ the error message as it tells you exactly what the problem is and where it is.

You're trying to assign an invalid parameter type which doesn't match what the callback within `setNotificationDeepLinkHandler` returns.
