### ISSUE TITLE
Changing push notifications icons

### ISSUE THREAD

**Issue by LRossiCenco** [oracle-samples/pushiomanager-flutter#7]
Hi! I've been trying to change the icons of my notifications but everything i've tried has failed. The library has 2 methods used for changing the icons **setDefaultLargeIcon(resourceId)** and **setDefaultSmallIcon(resourceId)**, but instead of using a string path for the resource, the method asks for a integer resource id. 
As far as i understand it, we can't get a resource id in Flutter, my question are:

- Has anybody changed the icons for their notifications?
- Has anybody used correctly the methods mentioned above?

Thx in advance!

**Comment by neerhaj** [comment]
With plugin v6.56.1, we have added two new APIs in Android plugin to change the large and small notification icon.

The method parameter is the name of the image file without extension. The image file can be put in `drawable` or `mipmap` directories.

```dart
PushIOManager.setNotificationLargeIcon("apple");
PushIOManager.setNotificationSmallIcon("orange");
```
